     create table family_tbl (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table user_role (
       user_id bigint not null,
        roles varchar(255)
    );

    create table usr_status_tbl (
       id bigint generated by default as identity,
        user_status varchar(255) not null,
        primary key (id)
    );

    create table usr_tbl (
       id bigint generated by default as identity,
        user_date date,
        user_family_status boolean,
        user_inn bigint,
        login varchar(100) not null,
        user_name varchar(100) not null,
        password varchar(100) not null,
        user_patronymic varchar(100) not null,
        education_enum varchar(255),
        user_last_name varchar(100) not null,
        family_id bigint,
        status_id bigint,
        primary key (id)
    );

    alter table user_role
       add constraint FKai2pqo6h0kui53p88y2ki1uln
       foreign key (user_id)
       references usr_tbl;

    alter table usr_tbl
       add constraint FKpa91q5dnc5rxkqhhwf7ftd7md
       foreign key (family_id)
       references family_tbl;

    alter table usr_tbl
       add constraint FK2giecjfymeosrutyc5eh9p8ms
       foreign key (status_id)
       references usr_status_tbl;